app/urls.py
from django.urls import path

from . import views
from .views import login_tem
from django.contrib import admin

app_name = 'app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('reports', views.reports, name='reports'),
    path('send_report', views.send_report, name='send_report'),
    path('quick_list', views.quick_list, name='quick_list'),
    path('quick_list_save', views.quick_list_save, name='quick_list_save'),
    path('kala_quick_list/<str:track_code>/', views.kala_quick_list, name='kala_quick_list'),
    path('login/', login_tem, name="login"),
    path('logout/', views.logout_tem, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("test/", views.test)
]

tadvinmasraf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'^admin/', admin.site.urls, name="admin"),
    path('', include('app.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('captcha/', include('ecaptcha.urls')),
]

templates/app/base.html
<html>
    <head>
        <title>تدوین مصرف تم</title>
        {% load static %}
        <link rel="icon" type="image/icon" href="{% static 'app/logo/logo.ico' %}">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        {% load static %}
        <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/CSS/persian.datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'app/CSS/jquery-ui.css' %}">
        <script src="{% static 'base/js/jQuery.js' %}"></script>
        <script src="{% static 'app/JS/jquery-ui.js' %}"></script>
        <script src="{% static 'app/JS/popper.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'app/CSS/bootstrap.min.css' %}">
        <script src="{% static 'app/JS/jquery.powertip.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'app/CSS/jquery.powertip.min.css' %}">
        <script src="{% static 'app/JS/persian.date.js' %}"></script>
        <script src="{% static 'app/JS/persian.datepicker.js' %}"></script>
        <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'app/CSS/style.css' %}">
        <script src="{% static 'app/JS/style.js' %}"></script>
    </head>
    <body>
        {# header #}
        <div id="header" class="fixed-top row">
            {# logo #}
            <div id="logo_box" class="col-3">
                {% load static %}
                <a href="{% url 'app:home' %}">
                    <img src="{% static 'app/logo/logo.png' %}" id="logo">
                </a>
            </div>
            {# title #}
            <div id="title_box" class="col-6">
                <div class="d-flex justify-content-center">
                    <div id="title" class="font-weight-bold rounded-pill">
                        جاری سازی ارتباطات و اطلاعات در مصرف با تدوین مصرف
                    </div>
                </div>
            </div>
            {# button #}
            <div id="btns" class="col-3">
                <a href="{% url 'app:quick_list' %}" id="quick_btn" class="btn rounded-pill">
                    <i class="far fa-list-alt"></i>
                    <span>کو‌ئیک لیست</span>
                </a>

                <div id="menu_btn">
                    <i id="menu_btn_icon" class="fas fa-bars"></i>
                    <div id="menu_btn_box" class="position-fixed float-left">
                        <a href="{% url 'app:quick_list' %}">
                            <div>
                                <i class="far fa-list-alt"></i>
                                <span>کو‌ئیک لیست</span>
                            </div>
                        </a>

                        <a href="">
                            <div>
                                <i class="far fa-file-alt"></i>
                                معرفی
                            </div>
                        </a>

                        <a href="">
                            <div>
                                 <i class="far fa-edit"></i>
                                 خدمات
                            </div>
                        </a>

                        <a href="">
                            <div>
                                <i class="far fa-bookmark"></i>
                                مقاله ها
                            </div>
                        </a>

                        <a href="">
                            <div>
                                <i class="far fa-envelope"></i>
                                تیکت
                            </div>
                        </a>

                    </div>
                </div>
            </div>
        </div>

        <div id="menu_box" class="d-block shadow container">
            <div id="menu" class="d-flex justify-content-start">
                <a href="">
                    <i class="far fa-file-alt"></i>
                    معرفی
                </a>

                <a href="">
                    <i class="far fa-edit"></i>
                    خدمات
                </a>

                <a href="">
                    <i class="far fa-bookmark"></i>
                    مقاله ها
                </a>

                <a href="">
                    <i class="far fa-envelope"></i>
                    تیکت
                </a>
            </div>
        </div>

        <div id="mask"></div>
        <div id="mask_share"></div>

        {% block content %}
        {% endblock %}

        {# footer #}
        <div id="footer">

            <div class="row">
                <div class="col-3 footer_item">
                    <div class="font-weight-bold">راهنمای تهییه لیست</div>
                    <ul>
                        <li>
                            <a href="{% url 'app:quick_list' %}">کوئیک لیست</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold">خدمات مشتریان</div>
                    <ul>
                        <li>
                            <a href="">نظرات</a>
                        </li>

                        <li>
                            <a href="{% url 'app:reports' %}">گزارشات</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold">ارتباط با ما</div>
                    <ul>
                        <li>
                            ایمیل: <a href="">tadvinmasraf@gmail.com</a>
                        </li>

                        <li>
                            شماره تماس: <a href="">---</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold"><span class="text-danger">تم</span> را در شبکه های اجتماعی دنبال کنید:</div>
                    <ul class="d-flex justify-content-start">
                        <li id="telegram">
                            <a href=""><i class="fab fa-telegram"></i></a>
                        </li>

                        <li id="instagram">
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="footer_mobile">
            <div id="footer_right" class="d-flex justify-content-around">
                <div class="col-6 footer_item">
                    <div class="font-weight-bold">راهنمای تهییه لیست</div>
                    <ul>
                        <li>
                            <a href="{% url 'app:quick_list' %}">کوئیک لیست</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 footer_item">
                    <div class="font-weight-bold">خدمات مشتریان</div>
                    <ul>
                        <li>
                            <a href="">نظرات</a>
                        </li>

                        <li>
                            <a href="{% url 'app:reports' %}">گزارشات</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="footer_left" class="d-flex justify-content-around">
                <div class="col-6 footer_item">
                    <div class="font-weight-bold">ارتباط با ما</div>
                    <ul>
                        <li>
                            ایمیل: <a href="">tadvinmasraf@gmail.com</a>
                        </li>

                        <li>
                            شماره تماس: <a href="">---</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 footer_item">
                    <div class="font-weight-bold"><span class="text-danger">تم</span> را در شبکه های اجتماعی دنبال کنید:</div>
                    <ul class="d-flex justify-content-start">
                        <li id="telegram">
                            <a href=""><i class="fab fa-telegram"></i></a>
                        </li>

                        <li id="instagram">
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

templates/app/home.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    تدوین مصرف (تم)
{% endblock %}
{% block content %}
    <div class="row" dir="rtl" style="padding: 10%">
        <div class="col-md-6 w-100 mt-4">
            <img alt="تدوین مصرف (تم)" class="img-fluid d-block float-right h-100 rounded"
                 src="{% static "base/css/images/logo.png" %}">
        </div>
        <div class="col-md-6 w-100 mt-4 ">
            <h3 class="font-weight-bold">
                چرا تدوین مصرف <span class="text-danger">تم</span>
            </h3>
            <div id="explain_txt">
                با توجه به اینکه مقوله مصرف یکی از الزامات دائمی و پیوسته
                انسان و جوامع می باشد و از آنجایی که انسان در هر شرایطی مجبور
                به مصرف می باشد ،لذا با توجه به اهمیت مصرف و تداوم همیشگی آن
                و تاثیری که مصرف و روشهای بررسی و انجام مصرف در سلامتی ،
                صرفه جویی در زمان و سرنوشت مالی و اقتصادی خانواده ها دارد ،
                لازم است خدمات جانبی پیرامون موضوع مصرف به مردم ارائه
                شود ،تا پروسه مصرف و تامین و کنترل آن با حداکثر
                کارایی در زندگی شخصی و اقتصادی انسانها تداوم یابد.
            </div>
            <br>
            <br>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {% include "base/footer.html" %}
{% endblock %}

templates/app/kala_quick_list.html
{% extends 'app/base.html' %}

{% block content %}
    <div id="kala_quick_list" class="container">
        <div class="row">
            <div class="col-6">
                <h4 id="kala_quick_list_title">
                    کوئیک لیست :
                </h4>
            </div>

            <div class="col-6">
                <div id="kala_quick_list_btns" class="rounded-pill d-flex">
                    <div id="kala_quick_list_share_btn" title="اشتراک گذاری" data-toggle="tooltip" data-placement="top"><i class="down_sign fas fa-share-alt"></i></div>
                    <div id="kala_quick_list_copy_btn" title="کپی" data-toggle="tooltip" data-placement="top"><i class="down_sign fas fa-copy"></i></div>
                    <div id="kala_quick_list_print" title="پرینت" data-toggle="tooltip" data-placement="top"><i class="fas fa-print"></i></div>
                    <div id="
                    kala_quick_list_serial" class="rounded-pill" title="شناسه سریال" data-toggle="tooltip" data-placement="right">{{ list.0.quick_list.track_code }}</div>
                </div>
            </div>
        </div>

        <div id="share_box">
            <i id="share_box_close" class="far fa-times-circle rounded-pill"></i><br>
            <span>فضای مجازی مورد نظر خود را انتخاب نمایید.</span><br>

            <div id="share_shapes_box">
                <div class="d-flex justify-content-around">
                    <i id="kala_quick_list_whatsApp_share" class="fab fa-whatsapp-square" title="whatsapp" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_twitter_share" class="fab fa-twitter-square" title="twitter" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_telegram_share" class="fab fa-telegram-plane" title="telegram" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_faceBook_share" class="fab fa-facebook-square" title="facebook" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_linkedin_share" class="fab fa-linkedin" title="linkedin" data-toggle="tooltip" data-placement="top"></i>
                </div><br>
                <div class="d-flex justify-content-around">
                    <i id="kala_quick_list_google_plus_share" class="fab fa-google-plus-square" title="google_plus" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_reddit_share" class="fab fa-reddit-square" title="reddit" data-toggle="tooltip" data-placement="top"></i>
                    <i id="kala_quick_list_pinterest_share" class="fab fa-pinterest-square" title="pinterest" data-toggle="tooltip" data-placement="top"></i>
                    <!-- {% load static %}
                    <i id="kala_quick_list_signal_share" title="signal" data-toggle="tooltip" data-placement="top"><img src="{% static 'app/icon/../../static/app/icon/signal.ico' %}"></i> -->
                    <i id="kala_quick_list_email_share" class="fas fa-envelope-square" title="email" data-toggle="tooltip" data-placement="top"></i>
                </div>
            </div>
        </div>

        <br><br>

        <div id="kala_quick_list_items">
            <div id="kala_quick_list_inf">
                <div id="kala_quick_list_date">
                    {{ list.0.quick_list.date }}
                </div>

                <div id="kala_quick_list_title">{{ list.0.quick_list.title }}</div>

                <div id="kala_quick_list_explain">{{ list.0.quick_list.explain }}</div>
            </div>

            {% for item in list %}
            <div class="kala_quick_list_item">
                <div class="row">
                    <div class="col-5">
                        <div class="kala_items_name">{{ item.name }}</div>
                    </div>

                    <div class="col-4">
                        <div class="kala_items_explain">{{ item.explain }}</div>
                    </div>

                    <div class="col-3 d-flex">
                        {% if item.explain == ' ' %}
                        <i class="kala_question_sign fas fa-question-circle disable_click" title="توضیحات ندارد" data-toggle="tooltip" data-placement="right"></i>
                        {% else %}
                        <i class="kala_question_sign fas fa-question-circle" title="توضیحات" data-toggle="tooltip" data-placement="right"></i>
                        {% endif %}
                        <div class="kala_items_num">{{ item.num }}</div>
                        <div class="kala_items_measurement">
                            {% if item.measurement == 0 %}
                            عدد
                            {% elif item.measurement == 1 %}
                            بسته
                            {% elif item.measurement == 2 %}
                            کیلوگرم
                            {% elif item.measurement == 3 %}
                            گرم
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/app/quick_list_new.html
{% extends 'base/base.html' %}
{% load static %}
{% load item_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/fontawesome.min.css' %}">
    <script src="{% static 'app/JS/jquery.formset.js' %}"></script>
    <script src="{% static 'base/js/main.js' %}"></script>
{% endblock %}
{% block content %}
    <div style="padding: 10%;width: 100%;" class="row" dir="rtl">
        <div class="col-md-12 transparent-80 light white-light" style="border-radius: 25px;padding: 0!important;">
            <div class="w3-container light blue-overflow-light"
                 style="border-top-left-radius: 25px; border-top-right-radius: 25px;padding: 0!important;">
                {% include "base/main_menu.html" %}
            </div>
            <div style="padding: 10px">

                <form action="." method="post" id="quick_list_form">
                    {% csrf_token %}
                    <div class="list_info">
                        <div id="list_name_box" class="d-flex">
                            <label>عنوان لیست :</label>
                            <button type="button" id="btn_title_voice" class="rounded voice_btn"><i
                                    class="fas fa-microphone-alt"></i></button>
                            <input type="text" id="list_name" name="title" class="form-control" autocomplete="off"
                                   required>
                        </div>

                        <div id="list_explain_box" class="d-flex">
                            <label>توضیحات لیست :</label>
                            <button type="button" id="btn_explain_voice" class="rounded voice_btn"><i
                                    class="fas fa-microphone-alt"></i></button>
                            <textarea type="text" id="list_explain" name="explain" class="form-control"
                                      required></textarea>
                        </div>
                    </div>
                    <div id="empty_list">
                        <div class="d-flex justify-content-center">
                            <i class="fas fa-clipboard-list"></i>
                        </div>
                        <div class="d-flex justify-content-center">
                            لیست خرید شما خالی است!
                        </div>
                    </div>
                    <div id="list_box" style="height: 500px">
                        {{ form.extra_formset_html }}
                    </div>


                    <div id='security_box'>
                        <div class='captcha_header'>لطفا کد امنیتی زیر را وارد نمایید.</div>
                        <div class="security_code">
                            <div class="row d-flex justify-content-around list_info" style="padding: 10px;margin: 10px">
                                {#                                {{ form.captcha }}#}
                                <input type="hidden" name="captcha_0" value="{{ form.captcha.field.widget.key }}"
                                       required="" id="id_captcha_0">
                                <div class="col-sm-2"></div>

                                <div class="col-sm-2">
                                    <img class=" captcha"
                                         src="{% url "ecaptcha-image"  form.captcha.field.widget.key %}"
                                         style="height: 60px">
                                    <button class='js-captcha-refresh'>
                                        <i class="fas fa-sync-alt" title="بازیابی کد" data-toggle="tooltip"
                                           data-placement="top"></i>
                                    </button>
                                </div>
                                <div class="userInput d-flex justify-content-center col-sm-6">
                                    <input type="text" name="captcha_1" class="form-control rounded d-block"
                                           placeholder="کد امنیتی ..." required>
                                </div>
                                <div class="col-sm-2"></div>

                            </div>
                        </div>
                    </div>

                    <button type="submit" id="quick_list_form_btn" class="form-control rounded-pill">ذخیره لیست</button>
                </form>
            </div>

            <div id="quick_list_sugestion" class="row" dir="rtl">
                <div class="col-10">
                    لطفا در صورت مشاهده مواردی که در کوئیک لیست موجود نیستند، آنها را از طریق لینک مقابل گزارش دهید.&nbsp;&nbsp;
                    <a href="">ادامه...</a>
                </div>

                <div class="col-2 d-flex justify-content-start">
                    <i class="fas fa-shopping-cart"></i>
                    <div id="basket_items_num"></div>
                </div>
            </div>
        </div>
    </div>
    {% include "base/menu_script.html" %}
{% endblock %}

templates/app/reports.html
<html>
    <head>
        <title>تدوین مصرف تم</title>
        {% load static %}
        <link rel="icon" type="image/icon" href="{% static 'app/logo/../../static/app/logo/logo.ico' %}">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        {% load static %}
        <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/../../static/app/fontawesome/fontawesome-free-5.14.0-web/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'app/fontawesome/fontawesome-free-5.14.0-web/css/../../static/app/fontawesome/fontawesome-free-5.14.0-web/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/CSS/../../static/app/CSS/jquery-ui.css' %}">
        <script src="{% static 'app/JS/../../static/app/JS/jQuery.js' %}"></script>
        <script src="{% static 'app/JS/../../static/app/JS/jquery-ui.js' %}"></script>
        <script src="{% static 'app/JS/../../static/app/JS/popper.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'app/CSS/../../static/app/CSS/bootstrap.min.css' %}">
        <script src="{% static 'app/JS/../../static/app/JS/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'app/CSS/../../static/app/CSS/style.css' %}">
        <script src="{% static 'app/JS/../../static/app/JS/style.js' %}"></script>
    </head>
    <body>
        {# header #}
        <div id="code_img" class="shadow">

        </div>

        <div id="code_img_txt">
            <h4 class="text-danger">گزارش خطا</h4>
            <div>
                در صورت مشاهده نقص عملکرد، میتوانید با گزارش در این فرم ما را در بهتر ساختن
                سامانه یاری کنید. پس از بررسی گزارش توسط تیم مربوطه در اسرع وقت مشکل رفع
                خواهد شد.
            </div>
        </div>

        <div id="gratitude_txt" class="d-flex justify-content-center sticky-top">
            <div class="font-weight-bold">
                ممنون از شما که ما را در بهبود سامانه یاری میکنید.
            </div>
        </div>

        <div id="report_required">
            <h6 class="font-weight-bold">گزارش خطا</h6>
            <div>
                لطفا فرم زیر را کامل نمایید.
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <form id="report_form" action="{% url 'app:send_report' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="report_title">موضوع :</label>
                    {% if title_error %}
                    <span class="text-danger" style="font-size: 0.8em">{{ title_error }}</span>
                    <input type="text" name="report_title" id="report_title" class="form-control">
                    {% elif text_error %}
                    <input type="text" name="report_title" id="report_title" class="form-control" value="{{ report_title }}">
                    {% else %}
                    <input type="text" name="report_title" id="report_title" class="form-control">
                    {% endif %}
                </div>

                <div class="form-group" id="report_txt_box">
                    <label for="report_txt">متن گزارش :</label>
                    {% if text_error %}
                    <span class="text-danger" style="font-size: 0.8em">{{ text_error }}</span>
                    <textarea name="report_text" id="report_txt" class="form-control"></textarea>
                    {% elif title_error %}
                    <textarea name="report_text" id="report_txt" class="form-control">{{ report_text }}</textarea>
                    {% else %}
                    <textarea name="report_text" id="report_txt" class="form-control"></textarea>
                    {% endif %}
                </div>

                <div class="form-group" id="report_btn">
                    <button type="submit" class="float-left rounded-pill">ثبت و ارسال</button>
                    {% if message %}
                        <span class="text-success">{{ message }}</span>
                    {% endif %}
                </div>
            </form>
        </div>

        <div id="rule_box">
            <h5 class="font-weight-bold">ضوابط و قوانین</h5>
            <div>
                لطفا توجه داشته باشید قبل از برطرف شدن خطای گزارش شده، هیچگونه اطلاعاتی در مورد آن را عمومی نکرده یا با دیگران به اشتراک نگذارید.
                 همچنین به هیچ عنوان از مشکلات که یافته‌اید، بهره‌برداری و سوءاستفاده نکنید و به قوانین کشور پایبند باشید.
                 با توجه به اهمیت خطای گزارش شده از سوی شما، ما در سریعترین زمان پیگیر گزارش شما خواهیم بود.
            </div>
        </div>

        {# footer #}
        <div id="footer">
            <div class="row">
                <div class="col-3 footer_item">
                    <div class="font-weight-bold">راهنمای تهییه لیست</div>
                    <ul>
                        <li>
                            <a href="{% url 'app:quick_list' %}">کوئیک لیست</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold">خدمات مشتریان</div>
                    <ul>
                        <li>
                            <a href="">نظرات</a>
                        </li>

                        <li>
                            <a href="{% url 'app:reports' %}">گزارشات</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold">ارتباط با ما</div>
                    <ul>
                        <li>
                            ایمیل: <a href="">tadvinmasraf@gmail.com</a>
                        </li>

                        <li>
                            شماره تماس: <a href="">---</a>
                        </li>
                    </ul>
                </div>

                <div class="col-3 footer_item">
                    <div class="font-weight-bold"><span class="text-danger">تم</span> را در شبکه های اجتماعی دنبال کنید:</div>
                    <ul class="d-flex justify-content-start">
                        <li id="telegram">
                            <a href=""><i class="fab fa-telegram"></i></a>
                        </li>

                        <li id="instagram">
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="footer_mobile">
            <div id="footer_right" class="d-flex justify-content-around">
                <div class="col-6 footer_item">
                    <div class="font-weight-bold">راهنمای تهییه لیست</div>
                    <ul>
                        <li>
                            <a href="">کوئیک لیست</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 footer_item">
                    <div class="font-weight-bold">خدمات مشتریان</div>
                    <ul>
                        <li>
                            <a href="">نظرات</a>
                        </li>

                        <li>
                            <a href="">گزارشات</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div id="footer_left" class="d-flex justify-content-around">
                <div class="col-6 footer_item">
                    <div class="font-weight-bold">ارتباط با ما</div>
                    <ul>
                        <li>
                            ایمیل: <a href="">tadvinmasraf@gmail.com</a>
                        </li>

                        <li>
                            شماره تماس: <a href="">---</a>
                        </li>
                    </ul>
                </div>

                <div class="col-6 footer_item">
                    <div class="font-weight-bold"><span class="text-danger">تم</span> را در شبکه های اجتماعی دنبال کنید:</div>
                    <ul class="d-flex justify-content-start">
                        <li id="telegram">
                            <a href=""><i class="fab fa-telegram"></i></a>
                        </li>

                        <li id="instagram">
                            <a href=""><i class="fab fa-instagram"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>